name: SimpleGranter
version: '${version}'
main: com.jodexindustries.simplegranter.SimpleGranter
authors: [_Jodex__]
description: Simple grant plugin for minecraft server
api-version: '1.16'
softdepend:
  - Vault
  - LuckPerms
commands:
  grant:
    aliases: ['simplegranter']
    permission: simplegranter.grant
libraries:
  - com.j256.ormlite:ormlite-jdbc:6.1