name: SimpleGranter
version: '${version}'
main: com.jodexindustries.simplegranter.SimpleGranter
authors: [_Jodex__]
description: Simple grant plugin for minecraft server
depend:
  - Vault
commands:
  grant:
    aliases: ['simplegranter']
    permission: simplegranter.grant