name: SimpleGranter
version: '${version}'
main: com.jodexindustries.simplegranter.LegacyGranter
authors: [_Jodex__]
description: Simple grant plugin for minecraft server
softdepend:
  - Vault
  - LuckPerms
commands:
  grant:
    aliases: ['simplegranter']
    permission: simplegranter.grant