Settings:
  PermissionDriver: luckperms # or vault
  MySql:
    Enabled: false
    Host: 'localhost'
    Port: 3306
    DataBase: 'nameDataBase'
    User: 'root'
    Password: 'password'
  Groups:
    admin:
      premium: 1
      vip: 2
  Levels:
    admin: 10
    premium: 2
    vip: 1
    default: 0
  GiveCommand: lp user %target% parent set %group%
  GiveBroadCast:
    - "&fPlayer &c%player% &fgifted group %groupprefix%&rto player &e%target%"

Messages:
  Help:
    - '&7» &a/grant &7(&cnick&7) (&dgroup&7) &8- &eGrant group for player'
    - '$admin&7» &a/grant &creload &8- &eReload configs'
  NoPermissions: "&cYou don't have enough permissions!"
  ReloadConfig: "&aConfig reloaded successfully!"
  PlayerNotFound: "&cPlayer not found!"
  GiveYourself: "&cYou can't give group yourself!"
  AlreadyIssued: "&cThe issuing limit for this group has been reached."
  CannotGrant: "&cYour group can't grant this privilege"
  CannotGrantAnyOthers: "&cYour group cannot issue any others"
  GroupNotFound: "&cNo group found."
  TargetGroupLevelBigger: "&cThe player's group level is greater than or equal to the one you want to give him."
