name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build all modules
        run: ./gradlew clean build --parallel

      - name: Upload Legacy JAR
        uses: actions/upload-artifact@v4
        with:
          path: legacy/build/libs/*.jar
          name: 'SimpleGranter-1.12.2-1.16.4'

      - name: Upload Modern JAR
        uses: actions/upload-artifact@v4
        with:
          path: modern/build/libs/*.jar
          name: 'SimpleGranter-1.16.5+'
